### ISSUE TITLE
erreur au demarrage

### ISSUE THREAD

**Issue by Miauto** [rfxcom2mqtt/backend#3]
Salut,
bonne idée ce projet, si j'arrive a le faire fonctionner, cela rendra uniforme l'architecture de l'ensemble des protocoles.
merci a toi.

### **Describe the bug**
l'image docker plante au demarrage

j'ai copié le docker compose et adapté le port, mais cela plante.
voici le log du container

### **LOG**
```
2024-03-26T03:12:56.167197412Z /usr/local/lib/node_modules/ts-node/src/index.ts:859

2024-03-26T03:12:56.167231291Z     return new TSError(diagnosticText, diagnosticCodes, diagnostics);

2024-03-26T03:12:56.167237583Z            ^

2024-03-26T03:12:56.169450369Z TSError: ⨯ Unable to compile TypeScript:

2024-03-26T03:12:56.169476834Z src/utils/logger.ts(73,17): error TS2339: Property 'warning' does not exist on type 'Logger'.

2024-03-26T03:12:56.169482402Z src/utils/logger.ts(77,17): error TS2339: Property 'warning' does not exist on type 'Logger'.

2024-03-26T03:12:56.169486648Z 

2024-03-26T03:12:56.169490396Z     at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:859:12)

2024-03-26T03:12:56.169494392Z     at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:863:19)

2024-03-26T03:12:56.169498816Z     at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1077:36)

2024-03-26T03:12:56.169503837Z     at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1433:41)

2024-03-26T03:12:56.169508330Z     at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1617:30)

2024-03-26T03:12:56.169529967Z     at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)

2024-03-26T03:12:56.169535703Z     at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)

2024-03-26T03:12:56.169541236Z     at Module.load (node:internal/modules/cjs/loader:1205:32)

2024-03-26T03:12:56.169546776Z     at Function.Module._load (node:internal/modules/cjs/loader:1021:12)

2024-03-26T03:12:56.169551536Z     at Module.require (node:internal/modules/cjs/loader:1230:19) {

2024-03-26T03:12:56.169556450Z   diagnosticCodes: [ 2339, 2339 ]

2024-03-26T03:12:56.169562206Z }
```

une idée ?

merci

**Comment by sguernion** [comment]
Salut,

je ne reproduit pas le problème.

peux tu m'envoyer ton fichier docker-compose et le fichier de conf "config.yml" ?

et quel est l'architecture sur lequel tu lance le container (amd64, arm) ?

**Comment by Miauto** [comment]
j'ai mis plus bas le fichier.
le seul élément qui peut etre en erreur est l'achitecture, docker tourne sous debian x86_64

**docker-compose**

```
version: '3.8'
services:
  rfxcom2mqtt:
    container_name: rfxcom2mqtt
    image: rfxcom2mqtt/rfxcom2mqtt
    restart: unless-stopped
    volumes:
      - /app/rfxcom2mqtt/data:/app/data:rw
    environment:
      - TZ=Europe/Paris
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-RFXCOM_RFXtrx433_04VKC0KK-if00-port0:/dev/ttyACM0
```

le fichier config est une copie simple de github
```

healthcheck:
  enabled: false
  cron: '*/2 * * * *'
cacheState:
  enable: true
  saveInterval: 1
homeassistant:
  discovery: true
  discovery_topic: homeassistant
  discovery_device: rfxcom2mqtt
devices:
  - id: 0x011Bmocked_device2
    units:
      - unitCode: 1
        name: AC_notuse_1
mqtt:
  base_topic: rfxcom2mqtt
  include_device_information: false
  qos: 0
  retain: true
  server: mqtt://192.168.1.205:1883
  username: jeedom
  password: EWxOc844abT8KgpL3KV9WJ0xHH
rfxcom:
  debug: false
  receive:
    - temperaturehumidity1
    - homeconfort
    - lighting1
    - lighting2
    - lighting3
    - lighting4
    - remote
    - security1
  usbport: mock
  transmit:
    repeat: 4
    lighting1:
      - X10
      - ARC
      - ELRO
      - PHILIPS_SBC
    lighting2:
      - AC
      - HOMEEASY_EU
    lighting3:
      - KOPPLA
    lighting4:
      - PT2262
frontend:
  enabled: true
  host: 0.0.0.0
  port: 8891
```

**Comment by Miauto** [comment]
j'ai compris d'ou venais mon erreur.

le port usb 😅

j'arrive a voir les equipements.
maintenant faut que je comprenne comment tu envoie une commande depuis HA.
